---

- name: Isilon Base Configuration
  gather_facts: false
  hosts: localhost
  vars:
  collections:
  - dellemc.powerscale

  tasks:
    # Missing: add Evaluation licences
    # Please, do it manually with following OneFS CLI command:
    # isi license add --evaluation Smartconnect_advanced --evaluation Smartpools --evaluation SnapshotIQ --evaluation SyncIQ --evaluation Smartquotas 

    - name: Enable SBR
      dellemc.powerscale.networksettings:
        onefs_host: "{{ pscale_host }}"
        api_user: "{{ pscale_user }}"
        api_password: "{{ pscale_password }}"
        verify_ssl: "{{ verify_ssl }}"

        enable_source_routing: true
        state: "present"


    - name: Configure Management Groupnet
      dellemc.powerscale.groupnet:
        onefs_host: "{{ pscale_host }}"
        api_user: "{{ pscale_user }}"
        api_password: "{{ pscale_password }}"
        verify_ssl: "{{ verify_ssl }}"

        groupnet_name: "{{groupnet0.name}}"
        dns_servers: "{{groupnet0.dns_servers}}"
        dns_server_state: "add"
        dns_search_suffix: "{{groupnet0.dns_search_suffix}}"
        dns_search_suffix_state: "add"
        state: "present"

    - name: Configure Management Subnet
      dellemc.powerscale.subnet:
        onefs_host: "{{ pscale_host }}"
        api_user: "{{ pscale_user }}"
        api_password: "{{ pscale_password }}"
        verify_ssl: "{{ verify_ssl }}"

        groupnet_name: "{{ groupnet0.name }}"
        subnet_name: "{{ subnet0.name }}"
        netmask: "{{ subnet0.netmask }}"
        subnet_params:
          gateway: "{{ subnet0.gateway }}"
          vlan_enabled: false
          mtu: 1500
          sc_service_addrs: 
            - start_range: "{{ subnet0.sc_service_addrs_start }}"
              end_range: "{{ subnet0.sc_service_addrs_end }}"
          sc_service_addrs_state: "add"
        state: "present"

    - name: Build ifaces variable
      set_fact:
        ifaces: "{{ ifaces | default ([]) + [{'lnn': item, 'iface': ippool_mgmt.ifaces_range.iface }]}}"
      loop: "{{ ippool_mgmt.ifaces_range.lnn }}"

    - name: Configure Management IP Pool
      dellemc.powerscale.networkpool:
        onefs_host: "{{ pscale_host }}"
        api_user: "{{ pscale_user }}"
        api_password: "{{ pscale_password }}"
        verify_ssl: "{{ verify_ssl }}"

        groupnet_name: "{{ groupnet0.name }}"
        subnet_name: "{{ subnet0.name }}"
        pool_name: "{{ ippool_mgmt.name }}"
        state: "present"
        additional_pool_params:
          ranges: "{{ ippool_mgmt.ranges }}"
          ifaces: "{{ ifaces }}"
          iface_state: "add"
        
    - name: Configure NTP Sources
      dellemc.powerscale.settings:
        onefs_host: "{{ pscale_host }}"
        api_user: "{{ pscale_user }}"
        api_password: "{{ pscale_password }}"
        verify_ssl: "{{ verify_ssl }}"
        
        ntp_servers: "{{ ntp_servers }}"
        state: "present"

    - name: Configure Active Directory integration
      dellemc.powerscale.ads:
        onefs_host: "{{ pscale_host }}"
        api_user: "{{ pscale_user }}"
        api_password: "{{ pscale_password }}"
        verify_ssl: "{{ verify_ssl }}"

        domain_name: "{{ ad_domain_name }}"
        ads_user: "{{ ad_domain_adminname }}"
        ads_password: "{{ ad_domain_adminpassword}}"
        state: "present"

    - name: Create custom NAS Administrators local group
      dellemc.powerscale.group:
        onefs_host: "{{ pscale_host }}"
        api_user: "{{ pscale_user }}"
        api_password: "{{ pscale_password }}"
        verify_ssl: "{{ verify_ssl }}"

        access_zone: "System"
        provider_type: "local"
        group_name: "NAS_Admins"
        group_id: 2222
        state: "present"
     
    - name: Create custom Administration Role
      dellemc.powerscale.role:
        onefs_host: "{{ pscale_host }}"
        api_user: "{{ pscale_user }}"
        api_password: "{{ pscale_password }}"
        verify_ssl: "{{ verify_ssl }}"
     
        role_name: "Corp_NAS_Admins"
        description: "Custom priviledges for the company NAS administrators"
        access_zone: "System"
        privileges:
        - name: "Antivirus"
          permission: "w"
          state: "absent"
        - name: "Audit"
          permission: "w"
          state: "present"
        - name: "Auth"
          permission: "w"
          state: "present"
        - name: "Certificate"
          permission: "w"
          state: "present"
        - name: "CloudPool"
          permission: "w"
          state: "present"
        - name: "Cluster"
          permission: "w"
          state: "present"
        - name: "Cluster Mode"
          permission: "w"
          state: "present"
        - name: "Configuration"
          permission: "w"
          state: "present"
        - name: "Configure File Metadata"
          permission: "r"
          state: "present"
        - name: "Configure Platform API"
          permission: "w"
          state: "present"
        - name: "Console"
          permission: "r"
          state: "present"
        - name: "DataMover"
          permission: "w"
          state: "present"
        - name: "Devices"
          permission: "w"
          state: "present"
        - name: "ESRS Downloads Access"
          permission: "w"
          state: "present"
        - name: "Event"
          permission: "w"
          state: "present"
        - name: "File Filtering"
          permission: "w"
          state: "present"
        - name: "Firewall"
          permission: "w"
          state: "present"
        - name: "FTP"
          permission: "w"
          state: "present"
        - name: "Hardening"
          permission: "w"
          state: "present"
        - name: "HDFS"
          permission: "w"
          state: "present"
        - name: "HTTP"
          permission: "w"
          state: "present"
        - name: "IFV Access"
          permission: "w"
          state: "present"
        - name: "IPMI"
          permission: "w"
          state: "present"
        - name: "Job Engine"
          permission: "w"
          state: "present"
        - name: "Key Management"
          permission: "w"
          state: "present"
        - name: "License"
          permission: "w"
          state: "present"
        - name: "Monitoring"
          permission: "r"
          state: "present"
        - name: "Namespace Access"
          permission: "r"
          state: "present"
        - name: "Namespace Traverse"
          permission: "r"
          state: "present"
        - name: "NDMP"
          permission: "w"
          state: "present"
        - name: "Network"
          permission: "w"
          state: "present"
        - name: "NFS"
          permission: "w"
          state: "present"
        - name: "NTP"
          permission: "w"
          state: "present"
        - name: "Performance"
          permission: "w"
          state: "present"
        - name: "Platform API"
          permission: "r"
          state: "present"
        - name: "Privilege"
          permission: "w"
          state: "present"
        - name: "Privileged Delete"
          permission: "w"
          state: "present"
        - name: "Quota"
          permission: "w"
          state: "present"
        - name: "Remote Support"
          permission: "w"
          state: "present"
        - name: "Restricted Auth"
          permission: "w"
          state: "present"
        - name: "S3"
          permission: "w"
          state: "present"
        - name: "Settings"
          permission: "w"
          state: "present"
        - name: "Shutdown"
          permission: "r"
          state: "present"
        - name: "SmartPools"
          permission: "w"
          state: "present"
        - name: "SMB"
          permission: "w"
          state: "present"
        - name: "Snapshot"
          permission: "w"
          state: "present"
        - name: "SNMP"
          permission: "w"
          state: "present"
        - name: "SSH"
          permission: "r"
          state: "present"
        - name: "Statistics"
          permission: "w"
          state: "present"
        - name: "Support"
          permission: "r"
          state: "present"
        - name: "SyncIQ"
          permission: "w"
          state: "present"
        - name: "Time"
          permission: "w"
          state: "present"
        - name: "Upgrade"
          permission: "w"
          state: "present"
        - name: "WORM"
          permission: "w"
          state: "present"


        members:
          - name: "NAS_Admins"
            type: "group"
            provider_type: "local"
            state: "present"
        state: "present"