---
- name: Configure Lab Isilon
  gather_facts: false
  hosts: localhost
  vars_files:
    - vars/cv-isilon-1.yml
  collections:
  - dellemc.powerscale

  tasks:
    - name: Configure Groupnet
      dellemc.powerscale.groupnet:
        onefs_host: "{{ pscale_host }}"
        api_user: "{{ pscale_user }}"
        api_password: "{{pscale_password }}"
        verify_ssl: "{{verify_ssl}}"

        groupnet_name: "{{groupnet}}"
        dns_servers: "{{dns_servers}}"
        dns_server_state: "add"
        dns_search_suffix: "{{dns_search_suffix}}"
        dns_search_suffix_state: "add"
        state: "present"

    - name: Configure Subnet
      dellemc.powerscale.groupnet:
        onefs_host: "{{ pscale_host }}"
        api_user: "{{ pscale_user }}"
        api_password: "{{pscale_password }}"
        verify_ssl: "{{verify_ssl}}"

        groupnet_name: "{{groupnet}}"
        subnet_name: "{{subnet}}"
        netmask: "{{netmask}}"
        subnet_params:
          gateway: "{{gateway}}"
          vlan_enabled: false
          mtu: 1500
          sc_service_addrs: 
            - start_range: "{{sc_service_addrs_start}}"
              end_range: "{{sc_service_addrs_end}}"
            sc_service_addrs_state: "add"
        state: "present"

    - name: Configure IP Pool
      dellemc.powerscale.networkpool:
        onefs_host: "{{ pscale_host }}"
        api_user: "{{ pscale_user }}"
        api_password: "{{pscale_password }}"
        verify_ssl: "{{verify_ssl}}"

        groupnet_name: "{{groupnet}}"
        subnet_name: "{{subnet}}"
        pool_name: "{{ippool_mgmt.name}}"
        ifaces:
          - iface: "{{ ippool_mgmt.ifaces.iface }}"
          - lnn: "{{ ippool_mgmt.ifaces.lnn }}"
        state: "present"

    - name: General cluster config
      dellemc.powerscale.settings:
        onefs_host: "{{ pscale_host }}"
        api_user: "{{ pscale_user }}"
        api_password: "{{pscale_password }}"
        verify_ssl: "{{verify_ssl}}"
        
        ntp_servers: "{{ ntp_servers }}"
        state: "present"