---

- name: Get SMB share facts test
  gather_facts: false
  hosts: localhost
  vars:
  collections:
  - dellemc.powerscale

  tasks:
    - name: "Get Administrative c$ SMB share"
      dellemc.powerscale.smb:
        onefs_host: "{{ pscale_host }}"
        api_user: "{{ pscale_user }}"
        api_password: "{{pscale_password }}"
        verify_ssl: "{{ verify_ssl }}"

        access_zone: "System"
        share_name: "c$"
        permissions:
          - wellknown: "everyone"
            permission: "read"
            permission_type: "deny"
          - user_name: "thomas@clairvue.lab"
            permission: "read"
            permission_type: "deny"
            provider_type: "ads"
            state: "absent"

        state: "present"

      register: smb_share

- name: "Test Delete permission"
  hosts: pscale-nodes

  tasks:
    - name: "Remove default Everyone:read permission from c$ SMB share"
      command: "isi smb shares permission delete c$ --wellknown=Everyone -f"
      register: result
      ignore_errors: yes